#!/bin/bash
ps1_parse_git_branch() {
     git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

PS1_CHROOT='${debian_chroot:+($debian_chroot)}'
PS1_USER='\[\033[01;32m\]\u'
PS1_HOST='\[\033[01;31m\]\h\[\033[00m\]'
PS1_PATH='\[\033[01;34m\]\w\[\033[00m\]'
PS1_BRANCH='\[\033[33m\]$(ps1_parse_git_branch)\[\033[00m\]'
PS1_DATETIME='\D{[%d]} \t'
PS1_SIGNAL='\$ \n=>'

PS1="${PS1_CHROOT}${PS1_USER}@${PS1_HOST}:${PS1_PATH}${PS1_BRANCH} ${PS1_DATETIME} ${PS1_SIGNAL} "
