#!/bin/sh
PATH=$PATH:${HOME}/Bin
PATH=$PATH:${HOME}/Bin/node/bin
PATH=$PATH:~/.npm-global
PATH=$PATH:~/.npm-global/bin
PATH=$PATH:~/.config/composer/vendor/bin

export PATH=${PATH}:${HOME}/Android/Sdk/platform-tools
export PATH=${PATH}:${HOME}/Android/Sdk/tools
export PATH=${PATH}:/opt/redis-desktop-manager
