#!/bin/sh
docker_status () {
  /etc/init.d/docker status | grep "Active: " | awk -F " " '{ print $2 }'
}

docker_restart_if_inactive () {
  status=$(docker_status)
  echo "docker status: $status"
  if test "$status" != "active"
  then
    echo "fiewall restart"
    sudo /etc/init.d/firewall restart
    echo "docker restart"
    sudo /etc/init.d/docker restart
  fi
}

alias up='docker-compose up'
alias workspace='docker-compose up nginx redis mysql workspace'
alias down='docker-compose down'
