#!/bin/sh
docker_status () {
  /etc/init.d/docker status | grep "Active: " | awk -F " " '{ print $2 }'
}

docker_restart_if_inactive () {
  status=$(docker_status)
  echo "docker status: $status"
  if test "$status" != "active"
  then
    echo "fiewall restart"
    sudo /etc/init.d/firewall restart
    echo "docker restart"
    sudo /etc/init.d/docker restart
  fi
}

alias up='docker-compose up'
alias down='docker-compose down'

alias dclmysql='docker-compose logs mysql'
alias dcps='docker-compose ps'

alias art='docker-compose exec api php artisan'
alias artisan='docker-compose exec api php artisan'
alias migrate='docker-compose exec api php artisan migrate'
alias migrate:fresh='docker-compose exec api php artisan migrate:fresh'
alias migrate:refresh='docker-compose exec api php artisan migrate:refresh'
alias migrate:rollback='docker-compose exec api php artisan migrate:rollback'
alias refresh='docker-compose exec api php artisan migrator:refresh —seed'
alias rollback='docker-compose exec api php artisan migrator:rollback'
alias monitor:queries='docker-compose exec api php artisan monitor:queries'
alias monitor:laravel='docker-compose exec api php artisan monitor:laravel'
alias queries='docker-compose exec api php artisan monitor:queries'
alias tinker='docker-compose exec api php artisan tinker'
alias route:list='docker-compose exec api php artisan route:list'
alias migrator='docker-compose exec api php artisan migrator'
alias migrator:rollback='docker-compose exec api php artisan migrator:rollback'
alias migrator:fresh='docker-compose exec api php artisan migrator:fresh'
alias fresh='docker-compose exec api php artisan migrator:fresh'
alias composer='docker-compose exec api composer'

# nova
alias nova:action="docker-compose exec api php artisan nova:action"
alias nova:asset="docker-compose exec api php artisan nova:asset"
alias nova:base-resource="docker-compose exec api php artisan nova:base-resource"
alias nova:card="docker-compose exec api php artisan nova:card"
alias nova:field="docker-compose exec api php artisan nova:field"
alias nova:filter="docker-compose exec api php artisan nova:filter"
alias nova:install="docker-compose exec api php artisan nova:install"
alias nova:lens="docker-compose exec api php artisan nova:lens"
alias nova:partition="docker-compose exec api php artisan nova:partition"
alias nova:publish="docker-compose exec api php artisan nova:publish"
alias nova:resource="docker-compose exec api php artisan nova:resource"
alias nova:resource-tool="docker-compose exec api php artisan nova:resource-tool"
alias nova:theme="docker-compose exec api php artisan nova:theme"
alias nova:tool="docker-compose exec api php artisan nova:tool"
alias nova:trend="docker-compose exec api php artisan nova:trend"
alias nova:user="docker-compose exec api php artisan nova:user"
alias nova:value="docker-compose exec api php artisan nova:value"
