#!/bin/sh
source ~/shell/aliases/docker
source ~/shell/aliases/git
source ~/shell/aliases/laravel
source ~/shell/aliases/yarn
source ~/shell/aliases/sound
source ~/shell/aliases/laravel-docker
source ~/shell/aliases/npm

alias alias-reload="unalias -a; source ~/shell/index"
alias aliasreload="alias-reload"
alias nodocker="alias-reload"
