#!/bin/sh
source ~/shell/aliases/docker
source ~/shell/aliases/git
source ~/shell/aliases/laravel
source ~/shell/aliases/yarn
source ~/shell/aliases/sound
source ~/shell/aliases/laravel-docker
source ~/shell/aliases/npm

alias nodocker="source ~/shell/index"
