#!/bin/sh
pull_and_push_on_develop_and_master() {
  git checkout develop
  git pull
  git push origin develop
  git checkout master
  git merge develop
  git push origin master
  git checkout develop
}

alias dev='yarn dev'
alias dev:beta='yarn dev:beta'
alias dev:mobile='yarn dev:mobile'
alias logs='yarn logs'
alias start='yarn start --nolimit'
alias build='yarn build --nolimit'
alias prod='yarn prod --nolimit'
alias hot='yarn hot --nolimit'

alias release="pull_and_push_on_develop_and_master; yarn release"
alias release:beta="pull_and_push_on_develop_and_master; yarn release:beta"
alias release:desktop="pull_and_push_on_develop_and_master; yarn release:desktop"
alias release:mobile="pull_and_push_on_develop_and_master; yarn release:mobile"
alias deploy="pull_and_push_on_develop_and_master; yarn deploy"
